version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    volumes: 
      - ./webapp.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=webApp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    links:
      - mysql
    environment:
      - PMA_USER=user
      - PMA_PASSWORD=password
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - backend
networks:
  frontend:
  backend: